### ISSUE TITLE
Not working on safari on iOS

### ISSUE THREAD

**Issue by damanmokha** [opentok/opentok-rtc#511] opened 2019-08-01 06:13 UTC
Not working on safari iPhone, I tested the http://opentokrtc.com also, found out there is another link for safari, what are the changes in that? so that I can get my build also working on safari.
As it's not working right now, wanted to see what additional things I need to take care for safari.

**Comment by damanmokha** [comment] 2019-08-01 06:54
While I debugged more I am getting these errors in ios,

- `TypeError: undefined is not an object (evaluating 'this._audioLevelSampler.sample')`
- `Refused to set unsafe header "Content-Length"`
- `OT.exception :: title: Unexpected Server Response (2001) msg: publishMessageInvalid`
- `OT_UNEXPECTED_SERVER_RESPONSE: Session.publish :: Unexpected server response: publishMessageInvalid`

**Comment by msach22** [comment] 2019-08-01 23:00
@damanmokha Thanks for filing the issue. We're unable to reproduce this issue on our end. Could you also share the version of Safari this is happening on along with any more reproduction steps if you can? 

Please note that this will not work inside a webview because iOS webview does not support WebRTC.

**Comment by damanmokha** [comment] 2019-08-03 06:24
@msach22 Debugged more. It turns out, the device's camera was not working, and it didn't even ask for permission. It never said to me that no camera detected, so it was unclear why this was happening.
I think we should add some expectation if there is no camera detected on the device

**Comment by msach22** [comment] 2019-08-07 23:15
@damanmokha You can listen to events on the publisher object such as `accessDenied` or `accessDialogOpened` to know when the dialog for camera/microphone was requested. Please note that this is just a sample reference application.

For more information on Publisher events, please check: https://tokbox.com/developer/sdks/js/reference/Publisher.html

I'm going to go ahead and close this issue since this application works on iOS Safari.

**Closed by msach22** 2019-08-07 23:15 UTC
